name: hlint-from-scratch
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 0 * * *' # every day
jobs:
  hlint-from-scratch-ubuntu:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@v4
      - run: brew install automake
        if: matrix.os == 'macos'
      - run: echo "GHCLIB_AZURE='1'" >> $GITHUB_ENV
        shell: bash
      - run: ./hlint-from-scratch.sh --init="$HOME/project"
        shell: bash
      - run: cabal update
      - run: cabal install apply-refact
        if: matrix.os == 'ubuntu'
      # - run: ./hlint-from-scratch.sh --ghc-flavor="ghc-9.10.1" --stack-yaml=stack-exact.yaml --resolver=ghc-9.6.4 --no-checkout
      #   shell: bash
      - run: ./hlint-from-scratch.sh --ghc-flavor="" --stack-yaml=stack-exact.yaml --resolver=ghc-9.6.4 --no-checkout
        shell: bash
